#!/bin/env bash

emoticon=$( cat ~/.config/empicker/empicker_emojis | rofi -dmenu -show window | cut -d ' ' -f1 | tr -d '\n' )


if [[ -n $emoticon ]] ; then
	echo -n $emoticon | xclip -i -selection c
fi
