#!/bin/bash

# Asignando puerto por defecto
port="3000"

 if [[ -n $1 ]]; then
	 echo "Puerto ${1} seleccionado"
	 port=$1
 else
	 echo "Sin puerto seleccionado. Utilizando puerto por defecto ${port}"
 fi

ssh -i ~/.ssh/id_portfowradingtest -N -R 8001:localhost:$port test@danyael.xyz
echo "Enlace terminado"
