#!/bin/env bash

device_id=$( kdeconnect-cli -a --id-name-only | rofi -dmenu -show window | cut -d ' ' -f1 | tr -d '\n' )

rsync -aP $HOME/Documents/Books/ /run/user/$UID/$device_id/primary/Books
rsync -aP /run/user/$UID/$device_id/primary/Books/ $HOME/Documents/Books

